/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mempoolMempool } from "../../funcs/mempoolMempool.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.NetworkRequest$inboundSchema,
};

export const tool$mempoolMempool: ToolDefinition<typeof args> = {
  name: "mempool-mempool",
  description: `Get All Mempool Transactions

Get all Transaction Identifiers in the mempool`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await mempoolMempool(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
