/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { networkNetworkStatus } from "../../funcs/networkNetworkStatus.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.NetworkRequest$inboundSchema,
};

export const tool$networkNetworkStatus: ToolDefinition<typeof args> = {
  name: "network-network-status",
  description: `Get Network Status

This endpoint returns the current status of the network requested. Any NetworkIdentifier returned by /network/list should be accessible here.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await networkNetworkStatus(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
