/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { networkNetworkList } from "../../funcs/networkNetworkList.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.MetadataRequest$inboundSchema,
};

export const tool$networkNetworkList: ToolDefinition<typeof args> = {
  name: "network-network-list",
  description: `Get List of Available Networks

This endpoint returns a list of NetworkIdentifiers that the Rosetta server supports.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await networkNetworkList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
