/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsEventsBlocks } from "../funcs/eventsEventsBlocks.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Events extends ClientSDK {
  /**
   * [INDEXER] Get a range of BlockEvents
   *
   * @remarks
   * `/events/blocks` allows the caller to query a sequence of BlockEvents indicating which blocks were added and removed from storage to reach the current state. Following BlockEvents allows lightweight clients to update their state without needing to implement their own syncing logic (like finding the common parent in a reorg). `/events/blocks` is considered an "indexer" endpoint and Rosetta implementations are not required to complete it to adhere to the Rosetta spec. However, any Rosetta "indexer" MUST support this endpoint.
   */
  async eventsBlocks(
    request: models.EventsBlocksRequest,
    options?: RequestOptions,
  ): Promise<models.EventsBlocksResponse> {
    return unwrapAsync(eventsEventsBlocks(
      this,
      request,
      options,
    ));
  }
}
