/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Account } from "./account.js";
import { Block } from "./block.js";
import { Call } from "./call.js";
import { Construction } from "./construction.js";
import { Events } from "./events.js";
import { Mempool } from "./mempool.js";
import { Network } from "./network.js";
import { Search } from "./search.js";

export class Icpmcp extends ClientSDK {
  private _network?: Network;
  get network(): Network {
    return (this._network ??= new Network(this._options));
  }

  private _block?: Block;
  get block(): Block {
    return (this._block ??= new Block(this._options));
  }

  private _mempool?: Mempool;
  get mempool(): Mempool {
    return (this._mempool ??= new Mempool(this._options));
  }

  private _account?: Account;
  get account(): Account {
    return (this._account ??= new Account(this._options));
  }

  private _construction?: Construction;
  get construction(): Construction {
    return (this._construction ??= new Construction(this._options));
  }

  private _call?: Call;
  get call(): Call {
    return (this._call ??= new Call(this._options));
  }

  private _events?: Events;
  get events(): Events {
    return (this._events ??= new Events(this._options));
  }

  private _search?: Search;
  get search(): Search {
    return (this._search ??= new Search(this._options));
  }
}
