/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  Currency,
  Currency$inboundSchema,
  Currency$Outbound,
  Currency$outboundSchema,
} from "./currency.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ExemptionType,
  ExemptionType$inboundSchema,
  ExemptionType$outboundSchema,
} from "./exemptiontype.js";

/**
 * BalanceExemption indicates that the balance for an exempt account could change without a corresponding Operation. This typically occurs with staking rewards, vesting balances, and Currencies with a dynamic supply. Currently, it is possible to exempt an account from strict reconciliation by SubAccountIdentifier.Address or by Currency. This means that any account with SubAccountIdentifier.Address would be exempt or any balance of a particular Currency would be exempt, respectively. BalanceExemptions should be used sparingly as they may introduce significant complexity for integrators that attempt to reconcile all account balance changes. If your implementation relies on any BalanceExemptions, you MUST implement historical balance lookup (the ability to query an account balance at any BlockIdentifier).
 */
export type BalanceExemption = {
  /**
   * SubAccountAddress is the SubAccountIdentifier.Address that the BalanceExemption applies to (regardless of the value of SubAccountIdentifier.Metadata).
   */
  subAccountAddress?: string | undefined;
  /**
   * Currency is composed of a canonical Symbol and Decimals. This Decimals value is used to convert an Amount.Value from atomic units (Satoshis) to standard units (Bitcoins).
   */
  currency?: Currency | undefined;
  /**
   * ExemptionType is used to indicate if the live balance for an account subject to a BalanceExemption could increase above, decrease below, or equal the computed balance. * greater_or_equal: The live balance may increase above or equal the computed balance. This typically   occurs with staking rewards that accrue on each block. * less_or_equal: The live balance may decrease below or equal the computed balance. This typically   occurs as balance moves from locked to spendable on a vesting account. * dynamic: The live balance may increase above, decrease below, or equal the computed balance. This   typically occurs with tokens that have a dynamic supply.
   */
  exemptionType?: ExemptionType | undefined;
};

/** @internal */
export const BalanceExemption$inboundSchema: z.ZodType<
  BalanceExemption,
  z.ZodTypeDef,
  unknown
> = z.object({
  sub_account_address: z.string().optional(),
  currency: Currency$inboundSchema.optional(),
  exemption_type: ExemptionType$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "sub_account_address": "subAccountAddress",
    "exemption_type": "exemptionType",
  });
});

/** @internal */
export type BalanceExemption$Outbound = {
  sub_account_address?: string | undefined;
  currency?: Currency$Outbound | undefined;
  exemption_type?: string | undefined;
};

/** @internal */
export const BalanceExemption$outboundSchema: z.ZodType<
  BalanceExemption$Outbound,
  z.ZodTypeDef,
  BalanceExemption
> = z.object({
  subAccountAddress: z.string().optional(),
  currency: Currency$outboundSchema.optional(),
  exemptionType: ExemptionType$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    subAccountAddress: "sub_account_address",
    exemptionType: "exemption_type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BalanceExemption$ {
  /** @deprecated use `BalanceExemption$inboundSchema` instead. */
  export const inboundSchema = BalanceExemption$inboundSchema;
  /** @deprecated use `BalanceExemption$outboundSchema` instead. */
  export const outboundSchema = BalanceExemption$outboundSchema;
  /** @deprecated use `BalanceExemption$Outbound` instead. */
  export type Outbound = BalanceExemption$Outbound;
}

export function balanceExemptionToJSON(
  balanceExemption: BalanceExemption,
): string {
  return JSON.stringify(
    BalanceExemption$outboundSchema.parse(balanceExemption),
  );
}

export function balanceExemptionFromJSON(
  jsonString: string,
): SafeParseResult<BalanceExemption, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BalanceExemption$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BalanceExemption' from JSON`,
  );
}
