/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Case specifies the expected case for strings and hashes.
 */
export const Case = {
  UpperCase: "upper_case",
  LowerCase: "lower_case",
  CaseSensitive: "case_sensitive",
} as const;
/**
 * Case specifies the expected case for strings and hashes.
 */
export type Case = ClosedEnum<typeof Case>;

/** @internal */
export const Case$inboundSchema: z.ZodNativeEnum<typeof Case> = z.nativeEnum(
  Case,
);

/** @internal */
export const Case$outboundSchema: z.ZodNativeEnum<typeof Case> =
  Case$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Case$ {
  /** @deprecated use `Case$inboundSchema` instead. */
  export const inboundSchema = Case$inboundSchema;
  /** @deprecated use `Case$outboundSchema` instead. */
  export const outboundSchema = Case$outboundSchema;
}
